apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part-of: nimbus
  app.kubernetes.io/managed-by: kustomize

resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - hpa.yaml
  - ingress.yaml
  - pdb.yaml

images:
  - name: CHANGE_ME_ECR_REPO_URL
    newName: 123456789012.dkr.ecr.eu-west-1.amazonaws.com/nimbus-dev
    newTag: latest
